using System;

namespace c(sharp)
{
    class Program
    {
        static void Main(string[] args)
        {
          int a = new Random().Next(1,10); //a is random number generated by c#
         
          int b ; // b is to guess that generated number

while (b != a) //finite loop

//while(tue) infinite loop - we can use 'break' to make this loop finite

{
    Console.WriteLine("Guess the number (1 to 100): ");
    b = int.Parse(Console.ReadLine());
    if (b < a)
    {
        Console.WriteLine("You guessed too low! Try again!");
    }
    if (b > a)
    {
        Console.WriteLine("You guessed too high! Try again!");
    }
}
Console.WriteLine("You got it! Good job!");

   
        }
    }
}
